### ISSUE TITLE
Failing unit test Magento\Setup\Test\Unit\Model\InstallerTest

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#46] opened 2018-02-17 03:45 UTC
**Important: Use [libs-upgrade](https://github.com/magento-engcom/php-7.2-support/tree/libs-upgrade) branch as base for this task and as target for the PR.**

```
53) Magento\Setup\Test\Unit\Model\InstallerTest::testCheckExtensionsError
Failed asserting that exception of type "\Exception" is thrown.
```

See https://travis-ci.org/magento-engcom/php-7.2-support/jobs/342577316

**Comment by centerax** [comment] 2018-03-26 14:44
I could not reproduce the problem on my local Docker instance using the **libs-upgrade** branch running **PHP 7.2.3**.

**Comment by bbatsche** [comment] 2018-03-26 14:47
I can't reproduce this as well, I think this issue may have been resolved somewhere further up stream. @buskamuza should we go ahead and close this?

**Comment by buskamuza** [comment] 2018-03-26 15:44
Yes. Thanks, @centerax and @bbatsche 
Closed it.

**Closed as completed** 2018-03-29 04:25 UTC
Labels: fixed-in-libs-upgrade
