### ISSUE TITLE
Update zend-mail

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#12] opened 2017-12-26 19:40 UTC
**Important: Use [libs-upgrade](https://github.com/magento-engcom/php-7.2-support/tree/libs-upgrade) branch as base for this task and as target for the PR.**

Issues found in `zend-mail`:
1. `INTL_IDNA_VARIANT_2003` is deprecated, and used as default value for `idn_to_ascii()` and `idn_to_utf8()`. See http://php.net/manual/en/migration72.deprecated.php for details.
`\Zend\Mail\Header\AbstractAddressList::idnToAscii()` uses `idn_to_ascii()` with the default value. Explicit value `INTL_IDNA_VARIANT_UTS46` should be used as `$variant`. There is a PR to fix it - https://github.com/zendframework/zend-mail/pull/189
2. Usage of deprecated `$errcontext` parameter - create PR to the zend-mail repo

A use case to test: create a customer from the store front. Currently it fails with:
```
Deprecated Functionality: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /private/var/www/htdocs/m2-php72/magento2ce/vendor/zendframework/zend-mail/src/Header/AbstractAddressList.php on line 105 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Deprecated Functionality: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /private/var/www/htdocs/m2-php72/magento2ce/vendor/zendframework/zend-mail/src/Header/AbstractAddressList.php on line 105 at /private/var/www/htdocs/m2-php72/magento2ce/app/code/Magento/Email/Model/Transport.php:87, Exception(code: 0): Deprecated Functionality: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /private/var/www/htdocs/m2-php72/magento2ce/vendor/zendframework/zend-mail/src/Header/AbstractAddressList.php on line 105 at /private/var/www/htdocs/m2-php72/magento2ce/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []
```

Solution: update to ver. `2.9.0`

**Comment by buskamuza** [comment] 2018-01-26 03:03
Should be resolved in scope of https://github.com/magento-engcom/php-7.2-support/issues/24

**Comment by cieslix** [comment] 2018-03-24 14:26
I am closing this issue as I could not reproduce the problem as part of #distributed-cd.

 Environment:
- Magento 2.3-develop,
- PHP 7.2.3,
- deploy mode set to developer

Steps: 
- create account on storefront there was no error and email was correctly send,
- create new customer in admin panel there was no error and email was correctly send,

**Closed as completed** 2018-03-29 04:25 UTC
Labels: help wanted, 3rd-party dependency, backward-incompatible, requires-ee-changes, php-7.2, fixed-in-libs-upgrade
