### ISSUE TITLE
Can't save product with Opcache enabled

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#11] opened 2017-12-23 02:25 UTC
When saving a simple product, one of the following errors occurs:
```
Warning: Narrowing occurred during type inference. Please file a bug report on bugs.php.net in /private/var/www/htdocs/m2-php72/magento2ce/vendor/composer/ClassLoader.php on line 412
```
```
Warning: Invalid argument supplied for foreach() in /private/var/www/htdocs/m2-php72/magento2ce/app/code/Magento/ConfigurableProduct/Model/Product/VariationHandler.php on line 243
```

**Comment by cieslix** [comment] 2018-03-24 14:15
I am closing this issue as I could not reproduce the problem as part of #distributed-cd.

There was a problem in **Magento/ConfigurableProduct/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Configurable.php:161** with undefined index *'newProduct'*, but for it should be another task, when I've fixed it I was able to save product in admin panel.

Environment: 
- Magento 2.3-develop,
- Zend OPcache v7.2.3, PHP 7.2.3 ( docker php:7.2-fpm )
- **php.ini settings bellow** 
opcache.enable=1
opcache.revalidate_freq=3600
opcache.validate_timestamps=0
opcache.max_accelerated_files=7963
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1

Steps:
- Log into admin,
- Add new configurable product with variants,
- Add new simple product,

**Closed as completed** 2018-03-24 14:23 UTC
Labels: help wanted, php-7.2
